import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import getWeather from "../src/data/getWeather";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Weather Information</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="pt-8 pl-6">
        <div>
          <p>Today, 15 March 22</p>
          <h1 className="h1 font-bold text-2xl"></h1>
        </div>
      </header>
      <main>
        <div>
          <div className="w-56 h-56 m-auto mt-9 mb-9 bg-blue-700"> - </div>
        </div>
        <h1 className="text-center">Cloudy</h1>
        <div className="flex flex-row gap-10 justify-center mt-10 mb-20">
          <div>
            <p>Wind</p>
            <p>160</p>
          </div>
          <div>
            <p>Temp</p>
            <p>25°C</p>
          </div>
          <div>
            <p>Humidit</p>
            <p>30%</p>
          </div>
        </div>
        <div className="m-auto flex justify-center">
          <Link href={"/"}>
            <a className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-7 py-3 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
              Other City
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default Home;
