import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import SearchCity from "../src/components/SearchCity/InitialSearchPage";
import Link from "next/link";
import Header from "../src/components/Header/Header";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="max-w-[500px] m-auto">
        <img
          src="/images/weather.png"
          alt="Weather Image"
          className="w-[276px] m-auto mb-20"
        />
        <div className="bg-[#FFFFFF] h-[341px] rounded-t-[50px] m-auto">
          <div className="flex flex-col gap-[31px] drop-shadow-[0_4px_10px_rgba(0,0,0,0.25)] p-10">
            <h1 className="font-'Open_Sans' font-semibold text-[20px] text-center">
              Encontre as previsões meteorológicas em sua cidade
            </h1>
            <p className="font-'Open_Sans' text-slate-500 font-medium text-[16px] text-center">
              Etapas fáceis para prever o clima e facilitar o seu dia a dia
            </p>
            <Link href={"/search-city"}>
              <button className="py-[13px] px-[55px] bg-[#B8ADF0] rounded-[5px] text-white">
                INICIAR
              </button>
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
