import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import SearchCity from "../src/components/SearchCity";


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Weather Information</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <img
          src="https://www.clipartmax.com/png/full/129-1295102_weather-forecast-icon-partially-cloudy-png.png"
          alt="Weather Image"
          className="w-80 m-auto mt-20 mb-20"
        />
        
        <SearchCity />
       
      </main>
    </div>
  );
};

export default Home;
