import type { NextPage } from "next";
import { useContext, useEffect, useState } from "react";
import Head from "next/head";
import { ApiContext } from "../src/context/ApiContext";
import Conditions from "../src/components/Conditions/Conditions";
import InitialSearchPage from "../src/components/SearchCity/InitialSearchPage";
import Header from "../src/components/Header/Header";

const Home: NextPage = () => {
  const { data, loadingWeather } = useContext(ApiContext);
  const [inputText, setInputText] = useState<string>("");
  const [weatherInfos, setWeatherInfos] = useState<boolean>(false);

  return (
    <div>
      <Head>
        <title>Weather Information</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>
      <main>
        <div>
          <h1 className="ml-9 font-'Open_Sans' font-bold text-[#535353] text-[18px] mb-[18px]">
            Procure sua Cidade
          </h1>
          <div className="flex justify-center mb-[80px]">
            <div className="mb-3 xl:w-96 w-80">
              <div className="input-group relative flex flex-wrap items-stretch w-full mb-4 rounded">
                <input
                  type="search"
                  className="form-control relative flex-auto min-w-0 block w-full px-5 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none pl-5"
                  placeholder="Procurar..."
                  aria-label="Search"
                  aria-describedby="button-addon2"
                  onChange={(e) => {
                    setInputText(e.target.value);
                  }}
                />
                <button
                  className="absolute right-0 top-0 bottom-0 btn inline-block px-2 py-2.4 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700  focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out flex items-center"
                  onClick={() => {
                    loadingWeather(inputText);
                  }}
                >
                  <span
                    className="input-group-text flex items-center px-3 py-1.5 text-base font-normal text-gray-700 text-center whitespace-nowrap rounded"
                    id="basic-addon2"
                  >
                    <svg
                      aria-hidden="true"
                      focusable="false"
                      data-prefix="fas"
                      data-icon="search"
                      className="w-4"
                      role="img"
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 512 512"
                    >
                      <path
                        fill="white"
                        d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"
                      ></path>
                    </svg>
                  </span>
                </button>
              </div>
            </div>
          </div>
        </div>

        {data ? <Conditions /> : <InitialSearchPage />}
      </main>
    </div>
  );
};

export default Home;
